"""
Multi-sector configuration for Descomplicita procurement search.

Each sector defines a keyword set and exclusion list used by filter.py
to identify relevant procurement opportunities in PNCP data.
"""

from dataclasses import dataclass, field

from filter import KEYWORDS_EXCLUSAO, KEYWORDS_UNIFORMES


@dataclass(frozen=True)
class SectorConfig:
    """Configuration for a procurement sector."""

    id: str
    name: str
    description: str
    keywords: set[str]
    exclusions: set[str] = field(default_factory=set)
    # Tier-based keyword scoring (optional — if keywords_a is empty, uses flat keywords as tier A)
    keywords_a: set[str] = field(default_factory=set)  # Unambiguous (weight 1.0)
    keywords_b: set[str] = field(default_factory=set)  # Strong (weight 0.7)
    keywords_c: set[str] = field(default_factory=set)  # Ambiguous (weight 0.3)
    threshold: float = 0.6  # Minimum score to approve
    # High-precision terms for PNCP server-side palavraChave filtering (SE-001.1)
    search_keywords: list[str] = field(default_factory=list)
    # Sector-specific value range for filter_batch (SE-001.4)
    valor_min: float = 10_000.0
    valor_max: float = 10_000_000.0


SECTORS: dict[str, SectorConfig] = {
    # EPI-only contextual rule: handled at filter level via EPI_ONLY_KEYWORDS.
    # When calling filter_licitacao for vestuario, pass epi_only_keywords=EPI_ONLY_KEYWORDS
    # to reject procurements matching ONLY generic EPI terms without clothing context.
    "vestuario": SectorConfig(
        id="vestuario",
        name="Vestuário e Uniformes",
        description="Uniformes, fardamentos, roupas profissionais, EPIs de vestuário",
        keywords=KEYWORDS_UNIFORMES,
        exclusions=KEYWORDS_EXCLUSAO,
        keywords_a={
            "uniforme",
            "uniformes",
            "fardamento",
            "fardamentos",
            "farda",
            "fardas",
            "jaleco",
            "jalecos",
            "camiseta",
            "camisetas",
            "calça",
            "calças",
            "vestuario",
            "vestimenta",
            "vestimentas",
            "roupa",
            "roupas",
            "roupa profissional",
            "vestuario profissional",
            "indumentaria",
            "guarda-pó",
            "guarda-pós",
            "uniforme escolar",
            "uniforme hospitalar",
            "uniforme administrativo",
            "uniforme esportivo",
            "uniformes esportivos",
            "uniforme profissional",
            "fardamento militar",
            "fardamento escolar",
            "kit uniforme",
            "conjunto uniforme",
            "confeccao de uniforme",
            "confeccao de uniformes",
            "aquisição de uniforme",
            "aquisição de uniformes",
            "fornecimento de uniforme",
            "fornecimento de uniformes",
            "aquisição de vestuario",
            "fornecimento de vestuario",
            "aquisição de fardamento",
            "fornecimento de fardamento",
            "macacão",
            "macacoes",
            "bermuda",
            "bermudas",
            "saia",
            "saias",
            "sapato",
            "sapatos",
        },
        keywords_b={
            "camisa",
            "camisas",
            "camisa polo",
            "camisas polo",
            "blusa",
            "blusas",
            "agasalho",
            "agasalhos",
            "jaqueta",
            "jaquetas",
            "gandola",
            "gandolas",
            "jardineira",
            "jardineiras",
            "boné",
            "bonés",
            "confeccao de camiseta",
            "confeccao de camisetas",
            "epi vestuario",
            "epi vestimenta",
        },
        keywords_c={
            "epi",
            "epis",
            "equipamento de protecao individual",
            "equipamentos de protecao individual",
            "confeccao",
            "confeccoes",
            "costura",
            "bota",
            "botas",
            "meia",
            "meias",
            "avental",
            "aventais",
            "colete",
            "coletes",
        },
        search_keywords=["uniforme", "fardamento", "vestuario", "jaleco", "camiseta"],
    ),
    "alimentos": SectorConfig(
        id="alimentos",
        name="Alimentos e Merenda",
        description="Gêneros alimentícios, merenda escolar, refeições, rancho",
        keywords={
            "genero alimenticio",
            "generos alimenticios",
            "merenda",
            "merenda escolar",
            "refeicao",
            "refeicoes",
            "rancho militar",
            "cesta basica",
            "kit alimentacao",
            "fornecimento de alimentacao",
            "servico de alimentacao",
            "aquisicao de alimentos",
            "carne bovina",
            "carne suina",
            "leite",
            "laticinio",
            "laticinios",
            "arroz",
            "feijao",
            "farinha",
            "acucar",
            "hortifruti",
            "hortifrutigranjeiro",
            "agua mineral",
            "biscoito",
            "biscoitos",
            "bolacha",
            "bolachas",
            "macarrao",
            "conserva",
            "conservas",
            "enlatado",
            "enlatados",
            "congelado",
            "congelados",
            "sal",
            "oleo",
            "cafe",
            "fruta",
            "frutas",
            "verdura",
            "verduras",
            "legume",
            "legumes",
            "carne",
            "frango",
            "peixe",
            "pao",
            "paes",
            "bebida",
            "bebidas",
            "suco",
            "sucos",
        },
        keywords_a={
            "genero alimenticio",
            "generos alimenticios",
            "merenda",
            "merenda escolar",
            "cesta basica",
            "carne bovina",
            "carne suina",
            "arroz",
            "kit alimentacao",
            "fornecimento de alimentacao",
            "servico de alimentacao",
            "aquisicao de alimentos",
            "rancho militar",
            "hortifruti",
            "hortifrutigranjeiro",
            "acucar",
            "agua mineral",
            "congelado",
            "congelados",
            "conserva",
            "conservas",
            "enlatado",
            "enlatados",
        },
        keywords_b={
            "leite",
            "laticinio",
            "laticinios",
            "feijao",
            "farinha",
            "biscoito",
            "biscoitos",
            "bolacha",
            "bolachas",
            "macarrao",
            "refeicao",
            "refeicoes",
            "suco",
            "sucos",
            "verdura",
            "verduras",
            "legume",
            "legumes",
            # Standalone food terms — legitimate when alone (FPs guarded by exclusions)
            "cafe",
            "oleo",
            "sal",
            "carne",
            "frango",
            "peixe",
            "bebida",
            "bebidas",
            "fruta",
            "frutas",
            "pao",
            "paes",
        },
        keywords_c=set(),  # No tier C for alimentos — exclusions handle FPs
        exclusions={
            # "alimentação" in non-food context
            "alimentação de dados",
            "alimentacao eletrica",
            "alimentacao de energia",
            "alimentacao ininterrupta",
            "fonte de alimentacao",
            # "sal" in non-food context
            "sal de audiencia",
            "salario",
            "oleo lubrificante",
            "oleo diesel",
            "oleo hidraulico",
            "troca de oleo",
            # "oleo" in automotive context (complement existing)
            "oleo de motor",
            "oleo 2 tempos",
            "oleo dois tempos",
            "oleo de motosserra",
            "oleo de rocadeira",
            # "cafe" as equipment (not food)
            "moinho para cafe",
            "moinho de cafe",
            "maquina de cafe",
            "cafeteira",
            # "bebida" — exclude non-procurement
            "bebida alcoolica",
        },
        search_keywords=["alimento", "merenda", "genero alimenticio", "cesta basica", "hortifruti"],
        valor_min=5_000.0,
        valor_max=20_000_000.0,
    ),
    "informatica": SectorConfig(
        id="informatica",
        name="Informática e Tecnologia",
        description="Computadores, servidores, software, periféricos, redes",
        keywords={
            "computador",
            "computadores",
            "notebook",
            "notebooks",
            "desktop",
            "desktops",
            "impressora",
            "impressoras",
            "scanner",
            "scanners",
            "teclado",
            "teclados",
            "nobreak",
            "nobreaks",
            "software",
            "softwares",
            "licenca de software",
            "sistema operacional",
            "antivirus",
            "firewall",
            "roteador",
            "roteadores",
            "cabo de rede",
            "cabeamento estruturado",
            "memoria ram",
            "processador",
            "processadores",
            "tablet",
            "tablets",
            "toner",
            "toners",
            "cartucho",
            "cartuchos",
            "informatica",
            "tecnologia da informacao",
            "equipamento de informatica",
            "servidor",
            "servidores",
            "monitor",
            "monitores",
            "mouse",
            "mouses",
            "switch",
            "switches",
            "hd",
            "ssd",
            "storage",
            "projetor",
            "projetores",
            "placa de video",
        },
        keywords_a={
            "notebook",
            "notebooks",
            "impressora",
            "impressoras",
            "software",
            "softwares",
            "licenca de software",
            "toner",
            "toners",
            "cartucho",
            "cartuchos",
            "nobreak",
            "nobreaks",
            "firewall",
            "roteador",
            "roteadores",
            "informatica",
            "tecnologia da informacao",
            "equipamento de informatica",
            "cabo de rede",
            "cabeamento estruturado",
            "memoria ram",
            "processador",
            "processadores",
            "sistema operacional",
            "teclado",
            "teclados",
            "placa de video",
        },
        keywords_b={
            "computador",
            "computadores",
            "desktop",
            "desktops",
            "scanner",
            "scanners",
            "tablet",
            "tablets",
            "antivirus",
            "mouse",
            "mouses",
        },
        keywords_c={
            "servidor",
            "servidores",
            "monitor",
            "monitores",
            "switch",
            "switches",
            "hd",
            "ssd",
            "storage",
            "projetor",
            "projetores",
        },
        exclusions={
            "informática educativa",
            # "servidor" in non-IT context (people, not machines)
            "servidor publico",
            "servidores publicos",
            "servidor municipal",
            "servidores municipais",
            "servidor efetivo",
            "servidores efetivos",
            "servidor estadual",
            "servidores estaduais",
            "servidor federal",
            "servidores federais",
            "servidor comissionado",
            "servidores comissionados",
            "servidor temporario",
            "servidores temporarios",
            "servidor ativo",
            "servidores ativos",
            "servidor inativo",
            "servidores inativos",
            "remuneracao dos servidores",
            "salario dos servidores",
            "pagamento dos servidores",
            "folha de pagamento dos servidores",
            "servidores e colaboradores",
            "protecao dos servidores",
            # "servidores" in beneficiary/professional context
            "destinados aos servidores",
            "destinado aos servidores",
            "para os servidores",
            "para servidores",
            "dos servidores",
            "aos servidores",
            "servidores e vereadores",
            "vereadores e servidores",
            "servidores das secretarias",
            "servidores da prefeitura",
            "servidores da camara",
            "servidores do municipio",
            "uso dos servidores",
            "consumo dos servidores",
            "servidores que trabalham",
            "servidores que realizam",
            "formacao de servidores",
            "capacitacao de servidores",
            "qualificacao de servidores",
            "treinamento de servidores",
            # "monitor" in non-IT context
            "monitor de aluno",
            "monitor de alunos",
            "monitor de patio",
            "monitor de transporte",
            "monitor social",
            # "monitor" in medical/health context
            "monitor de glicose",
            "monitor de pressao",
            "glicosimetro",
            # "monitor" in education context
            "monitor escolar",
            "monitores escolares",
            # "switch" in non-IT context (unlikely but guard)
            "switch grass",
        },
        search_keywords=["informatica", "computador", "notebook", "impressora", "software"],
        valor_min=5_000.0,
        valor_max=50_000_000.0,
    ),
    "limpeza": SectorConfig(
        id="limpeza",
        name="Produtos de Limpeza",
        description="Materiais de limpeza, higienização, saneantes, descartáveis",
        keywords={
            "material de limpeza",
            "materiais de limpeza",
            "produto de limpeza",
            "produtos de limpeza",
            "detergente",
            "detergentes",
            "desinfetante",
            "desinfetantes",
            "alvejante",
            "alvejantes",
            "agua sanitaria",
            "saneante",
            "saneantes",
            "papel higienico",
            "papel toalha",
            "saco de lixo",
            "sacos de lixo",
            "luva de limpeza",
            "luvas de limpeza",
            "vassoura",
            "vassouras",
            "rodo",
            "rodos",
            "pano de chao",
            "esponja",
            "esponjas",
            "desengordurante",
            "limpa vidro",
            "material de higienizacao",
            "servico de limpeza",
            "limpeza e conservacao",
            "limpeza predial",
            "limpeza",
            "sabao",
            "sabonete",
            "cloro",
            "balde",
            "baldes",
            "cera",
            "higiene",
            "higienizacao",
            "descartaveis",
            "copa e cozinha",
            "inseticida",
        },
        keywords_a={
            "material de limpeza",
            "materiais de limpeza",
            "produto de limpeza",
            "produtos de limpeza",
            "detergente",
            "detergentes",
            "desinfetante",
            "desinfetantes",
            "alvejante",
            "alvejantes",
            "agua sanitaria",
            "saneante",
            "saneantes",
            "papel higienico",
            "papel toalha",
            "saco de lixo",
            "sacos de lixo",
            "luva de limpeza",
            "luvas de limpeza",
            "desengordurante",
            "limpa vidro",
            "material de higienizacao",
            "servico de limpeza",
            "limpeza e conservacao",
            "limpeza predial",
            "pano de chao",
            "cloro",
        },
        keywords_b={
            "vassoura",
            "vassouras",
            "rodo",
            "rodos",
            "esponja",
            "esponjas",
            "sabao",
            "sabonete",
            "copa e cozinha",
        },
        keywords_c={
            "limpeza",
            "higiene",
            "higienizacao",
            "descartaveis",
            "cera",
            "balde",
            "baldes",
            "inseticida",
        },
        exclusions={
            "limpeza de dados",
            "limpeza de terreno",
            "limpeza de terrenos",
            "limpeza de fossa",
            "limpeza de fossas",
            "limpeza de codigo",
            # "limpeza" in environmental/infrastructure context
            "limpeza de rio",
            "limpeza de lagoa",
            "limpeza de canal",
            "limpeza de corrego",
            "limpeza de bueiro",
            "limpeza de bueiros",
            "limpeza de galeria",
            "limpeza de galerias",
            "desassoreamento",
            "escavadeira",
            # "limpeza" in automotive context
            "limpeza pesada para veiculos",
            "limpeza automotiva",
            # "inseticida" in pest control services (not cleaning product)
            "nebulizacao",
            "desinsetizacao",
            "controle de pragas",
            "controle de vetores",
            # "cera" in non-cleaning context
            "cera perdida",  # lost-wax casting
            "cera ortodontica",
            # "higiene" in non-product context
            "higiene ocupacional",
            "higiene do trabalho",
            # "limpeza" in urban/public services context (not cleaning products)
            "limpeza urbana",
            "limpeza publica",
            "limpeza de via",
            "limpeza de vias",
            "limpeza de estrada",
            "limpeza de estradas",
            "limpeza de logradouro",
            "limpeza de logradouros",
            "servico de limpeza urbana",
            # "descartavel" in medical/surgical context (not cleaning supplies)
            "descartavel cirurgico",
            "descartavel hospitalar",
            "campo cirurgico descartavel",
            "kit cirurgico descartavel",
            "avental descartavel",
            "lencol descartavel",
        },
        search_keywords=["material de limpeza", "detergente", "desinfetante", "saneante", "papel higienico"],
        valor_min=2_000.0,
        valor_max=5_000_000.0,
    ),
    "mobiliario": SectorConfig(
        id="mobiliario",
        name="Mobiliário",
        description="Mesas, cadeiras, armários, estantes, móveis de escritório",
        keywords={
            "mobiliario",
            "mobilia",
            "movel",
            "moveis",
            "cadeira",
            "cadeiras",
            "armario",
            "armarios",
            "estante",
            "estantes",
            "gaveteiro",
            "gaveteiros",
            "escrivaninha",
            "escrivaninhas",
            "sofa",
            "sofas",
            "poltrona",
            "poltronas",
            "prateleira",
            "prateleiras",
            "biro",
            "mesa de reuniao",
            "mesa de escritorio",
            "mobiliario escolar",
            "carteira escolar",
            "carteiras escolares",
            "movel planejado",
            "moveis planejados",
            # Restored standalone terms (guarded by exclusions)
            "mesa",
            "mesas",
            "banco",
            "bancos",
            "balcao",
            "arquivo",
            "arquivos",
            "rack",
            "racks",
            "quadro branco",
            "lousa",
        },
        exclusions={
            "mesa de negociacao",
            "mesa redonda",
            "mesa de cirurgia",
            "mesa de bilhar",
            # "mesa" in non-furniture context (bed/bath linen)
            "roupa de cama mesa e banho",
            "cama mesa e banho",
            "roupa de mesa",
            # "móveis/móvel" in non-furniture context (portable/mobile)
            "equipamentos moveis",
            "equipamento movel",
            "unidade movel",
            "telefonia movel",
            # "banco" in non-furniture context
            "banco de dados",
            "banco central",
            "banco do brasil",
            "banco de sangue",
            "banco de leite",
            "banco de horas",
            "banco de talentos",
            "estabelecimento bancario",
            "instituicao bancaria",
            # "arquivo" in non-furniture context
            "arquivo morto",
            "arquivo digital",
            "arquivo pdf",
            "arquivo de dados",
            # "rack" in non-furniture context
            "rack de servidor",
            "rack de servidores",
            "rack de rede",
            # "rack" in IT context (complement existing)
            "rack 19 polegadas",
            "rack de telecomunicacao",
            "rack para equipamentos de informatica",
            # "banco" in financial context (complement existing)
            "servicos bancarios",
            "servico bancario",
            "arrecadacao bancaria",
            "taxa bancaria",
        },
        search_keywords=["mobiliario", "cadeira", "armario", "mesa de escritorio", "estante"],
        valor_min=5_000.0,
        valor_max=10_000_000.0,
    ),
    "papelaria": SectorConfig(
        id="papelaria",
        name="Papelaria e Material de Escritório",
        description="Papel, canetas, material de escritório, suprimentos administrativos",
        keywords={
            "papelaria",
            "material de escritorio",
            "papel a4",
            "papel sulfite",
            "caneta",
            "canetas",
            "lapis",
            "grampeador",
            "grampeadores",
            "clipe",
            "clipes",
            "envelope",
            "envelopes",
            "fichario",
            "caderno",
            "cadernos",
            "bloco de notas",
            "fita adesiva",
            "fita crepe",
            "marca texto",
            "pincel atomico",
            "etiqueta",
            "etiquetas",
            "calculadora",
            "calculadoras",
            "material escolar",
            "kit escolar",
            "material de expediente",
            # Restored standalone terms (guarded by exclusions)
            "papel",
            "papeis",
            "borracha",
            "borrachas",
            "cola",
            "colas",
            "tesoura",
            "tesouras",
            "grampo",
            "grampos",
            "pasta",
            "pastas",
            "agenda",
            "agendas",
            "expediente",
        },
        exclusions={
            "papel de parede",
            "papel moeda",
            "papel higienico",  # cleaning sector
            "papel toalha",  # cleaning sector
            # "borracha" in non-stationery context
            "borracha natural",
            "borracha de vedacao",
            "pneu",
            # "clipe" in non-stationery context (medical)
            "clipe de aneurisma",
            "clipes de aneurisma",
            "clipes de aneurismas",
            "opme",  # Órteses, Próteses e Materiais Especiais
            # "cola" in non-stationery context
            "coca cola",
            "cola cirurgica",
            # "pasta" in non-stationery context
            "pasta de dente",
            "pasta dental",
            "pasta de solda",
            # "grampo" in non-stationery context
            "grampo cirurgico",
            "grampo de cabelo",
            # "agenda" in non-product context
            "agenda de reuniao",
            "agenda legislativa",
            # "expediente" in non-product context
            "horario de expediente",
            "fora de expediente",
        },
        search_keywords=["material de escritorio", "papelaria", "papel sulfite", "material escolar", "caneta"],
        valor_min=1_000.0,
        valor_max=2_000_000.0,
    ),
    "saude": SectorConfig(
        id="saude",
        name="Saúde e Medicamentos",
        description="Medicamentos, insumos hospitalares, materiais de enfermagem, EPIs hospitalares",
        keywords={
            # Medicamentos - termos compostos (alta precisao)
            "medicamento",
            "medicamentos",
            "remedio",
            "remedios",
            "farmaco",
            "farmaceutico",
            "medicamento generico",
            "medicamento similar",
            "medicamento de referencia",
            "insumo hospitalar",
            "insumos hospitalares",
            "material hospitalar",
            "materiais hospitalares",
            # Formas farmaceuticas
            "comprimido",
            "comprimidos",
            "capsula",
            "capsulas",
            "ampola",
            "ampolas",
            "frasco-ampola",
            "pomada",
            "pomadas",
            "creme dermatologico",
            "solucao injetavel",
            "xarope",
            "xaropes",
            "suspensao oral",
            # Materiais de enfermagem/curativo
            "seringa",
            "seringas",
            "agulha",
            "agulhas",
            "luva cirurgica",
            "luva de procedimento",
            "gaze",
            "atadura",
            "ataduras",
            "soro",
            "soro fisiologico",
            "curativo",
            "curativos",
            "material de curativo",
            "cateter",
            "cateteres",
            "sonda",
            "sondas",
            "bisturi",
            "fio de sutura",
            "sutura",
            "equipo",
            "equipos",
            # Categorias terapeuticas
            "anestesico",
            "antibiotico",
            "anti-inflamatorio",
            "analgesico",
            "antipiretico",
            "vacina",
            "vacinas",
            "imunobiologico",
            "hemoderivado",
            "hemoderivados",
            "insulina",
            "hipoglicemiante",
            # Diagnostico
            "reagente laboratorial",
            "reagente",
            "reagentes",
            "kit diagnostico",
            "teste rapido",
            "tira reagente",
            "contraste radiologico",
            # EPIs hospitalares
            "mascara cirurgica",
            "avental hospitalar",
            "avental cirurgico",
            "touca cirurgica",
            "prope",
            # Termos gerais (guardados por exclusions)
            "material de enfermagem",
            "produto farmaceutico",
            "produto para saude",
            "dispositivo medico",
        },
        exclusions={
            # Saude em contexto nao-produto
            "saude financeira",
            "saude do solo",
            "saude animal",
            "medicamento veterinario",
            "uso veterinario",
            # Regulatorio (nao e produto)
            "vigilancia sanitaria",
            "anvisa",
            "registro de medicamento",
            "farmacovigilancia",
            # "soro" em contexto nao-medico
            "soro de leite",
            # "reagente" em contexto quimico industrial
            "reagente quimico industrial",
            # "sonda" em contexto nao-medico
            "sonda de perfuracao",
            "sonda espacial",
        },
        search_keywords=["medicamento", "hospitalar", "farmaceutico", "insumo hospitalar", "material hospitalar"],
        valor_min=1_000.0,
        valor_max=50_000_000.0,
    ),
    "veiculos": SectorConfig(
        id="veiculos",
        name="Veículos, Peças e Combustíveis",
        description="Veículos, peças automotivas, combustíveis, manutenção de frota",
        keywords={
            # Veiculos - termos compostos
            "veiculo",
            "veiculos",
            "automovel",
            "automoveis",
            "caminhao",
            "caminhoes",
            "onibus",
            "motocicleta",
            "motocicletas",
            "moto",
            "motos",
            "ambulancia",
            "ambulancias",
            "viatura",
            "viaturas",
            "caminhonete",
            "caminhonetes",
            "camionete",
            "van",
            "vans",
            "micro-onibus",
            "utilitario",
            # Combustiveis
            "combustivel",
            "combustiveis",
            "gasolina",
            "diesel",
            "oleo diesel",
            "etanol",
            "gnv",
            "gas natural veicular",
            "abastecimento",
            "posto de combustivel",
            # Pecas e manutencao veicular
            "peca automotiva",
            "pecas automotivas",
            "peca de reposicao",
            "pecas de reposicao",
            "pneu",
            "pneus",
            "bateria automotiva",
            "baterias automotivas",
            "filtro de oleo",
            "filtro de ar",
            "filtro de combustivel",
            "pastilha de freio",
            "disco de freio",
            "amortecedor",
            "amortecedores",
            "lubrificante",
            "lubrificantes",
            "oleo lubrificante",
            # Servicos veiculares
            "retifica",
            "funilaria",
            "lanternagem",
            "manutencao veicular",
            "manutencao de frota",
            "locacao de veiculo",
            "locacao de veiculos",
            "seguro veicular",
            "seguro de veiculo",
            "rastreamento veicular",
            "rastreador veicular",
            "lavagem de veiculo",
            "lavagem de frota",
            "revisao veicular",
        },
        exclusions={
            # "veiculo" em contexto nao-automotivo
            "veiculo de comunicacao",
            "veiculo de imprensa",
            "veiculo de informacao",
            # "pecas" em contexto nao-automotivo
            "pecas de roupa",
            "pecas processuais",
            "pecas juridicas",
            "pecas teatrais",
            # "bateria" em contexto nao-automotivo
            "bateria musical",
            "bateria de cozinha",
            "bateria de testes",
            # "filtro" em contexto nao-automotivo
            "filtro de agua",
            "filtro de linha",
            "filtro solar",
            # "abastecimento" em contexto nao-combustivel
            "abastecimento de agua",
            "abastecimento hidrico",
            # "abastecimento" in public water supply context
            "abastecimento publico",
            "sistema de abastecimento de agua",
        },
        search_keywords=["veiculo", "combustivel", "pneu", "peca automotiva", "manutencao veicular"],
        valor_min=20_000.0,
        valor_max=100_000_000.0,
    ),
    "engenharia": SectorConfig(
        id="engenharia",
        name="Engenharia e Construção",
        description="Obras, reformas, construção civil, pavimentação, infraestrutura",
        keywords={
            "construcao civil",
            "pavimentacao",
            "recapeamento",
            "recapeamento asfaltico",
            "manutencao predial",
            "impermeabilizacao",
            "pintura predial",
            "pintura de fachada",
            "instalacao eletrica",
            "instalacao hidraulica",
            "ar condicionado",
            "climatizacao",
            "saneamento basico",
            "terraplanagem",
            "projeto arquitetonico",
            "laudo tecnico",
            "obra de engenharia",
            "servico de engenharia",
            "alvenaria",
            "concreto armado",
            "concreto",
            "asfalto",
            "asfaltamento",
            "drenagem",
            "obra",
            "obras",
            "reforma",
            "reformas",
            "engenharia",
            "construcao",
            "edificacao",
            "ampliacao",
            "restauracao",
            "demolicao",
            "infraestrutura",
            "cimento",
            "aco",
            "ferro",
            "madeira",
            "tijolo",
            "tijolos",
            "areia",
            "brita",
            "cascalho",
            "telhado",
            "cobertura",
            "piso",
            "revestimento",
            "elevador",
            "elevadores",
        },
        keywords_a={
            "construcao civil",
            "pavimentacao",
            "recapeamento",
            "recapeamento asfaltico",
            "alvenaria",
            "terraplanagem",
            "concreto armado",
            "concreto",
            "manutencao predial",
            "impermeabilizacao",
            "pintura predial",
            "pintura de fachada",
            "instalacao eletrica",
            "instalacao hidraulica",
            "saneamento basico",
            "projeto arquitetonico",
            "laudo tecnico",
            "obra de engenharia",
            "servico de engenharia",
            "engenharia",
            "construcao",
            "edificacao",
            "demolicao",
            "cimento",
            "elevador",
            "elevadores",
        },
        keywords_b={
            "obra",
            "obras",
            "reforma",
            "reformas",
            "asfalto",
            "asfaltamento",
            "drenagem",
            "ampliacao",
            "restauracao",
            "ar condicionado",
            "climatizacao",
            "aco",
            "tijolo",
            "tijolos",
            "brita",
            "cascalho",
            "telhado",
        },
        keywords_c={
            "infraestrutura",
            "cobertura",
            "piso",
            "revestimento",
            "ferro",
            "madeira",
            "areia",
        },
        exclusions={
            "engenharia de software",
            "engenharia de dados",
            "engenharia social",
            # "reforma" in non-construction context
            "reforma administrativa",
            "reforma tributaria",
            "reforma curricular",
            "reforma politica",
            # "restauração" in non-construction context
            "restauração de dados",
            "restauração de arquivo",
            "restauração de backup",
            # "infraestrutura" in IT/telecom context
            "infraestrutura de ti",
            "infraestrutura de rede",
            "infraestrutura de dados",
            "infraestrutura como servico",
            "infraestrutura de comunicacao",
            "infraestrutura de telecomunicacao",
            "infraestrutura de telefonia",
            # "infraestrutura" in events/temporary context
            "infraestrutura temporaria",
            "infraestrutura para evento",
            "infraestrutura para eventos",
            # "infraestrutura" as department name (not construction)
            "secretaria de infraestrutura",
            "secretaria da infraestrutura",
            "secretaria municipal de infraestrutura",
            "secretaria municipal da infraestrutura",
            "diretoria de infraestrutura",
            # "obra" in non-construction context (keep specific, avoid blocking legit civil works)
            # NOTE: "mão de obra" removed — too aggressive, blocks legit civil works
            # like "fornecimento de material e mão de obra para reforma"
            # "construção" in non-civil context
            "construcao de cenario",
            "construcao de cenarios",
            "cenarios cenograficos",
            # "madeira" in non-construction context
            "carroceria de madeira",
            # "cobertura" in non-construction context
            "cobertura de seguro",
            "cobertura jornalistica",
            "cobertura vacinal",
            # "ferro" in non-construction context
            "ferro de passar",
            # Automotive services that mention "infraestrutura"
            "servicos de borracharia",
            # Sports context matching "areia" (sand courts)
            "arbitragem",
            # "infraestrutura" in connectivity/logistics context (not civil works)
            "infraestrutura de conectividade",
            "infraestrutura de fibra",
            "infraestrutura de fibra optica",
            "infraestrutura produtiva",
            "infraestrutura logistica",
            # "cobertura" in insurance/aviation/health context (not roofing)
            "cobertura total",
            "cobertura ambulatorial",
            "cobertura veicular",
            "cobertura aerea",
            "cobertura aeronautica",
            "cobertura de casco",
            "cobertura hospitalar",
            "cobertura obstetra",
            "cobertura obstétrica",
        },
        search_keywords=["obra", "construcao civil", "pavimentacao", "reforma predial", "engenharia"],
        valor_min=50_000.0,
        valor_max=500_000_000.0,
    ),
    "hospitalar": SectorConfig(
        id="hospitalar",
        name="Equipamentos e Material Hospitalar",
        description="Equipamentos médicos, laboratoriais, odontológicos, mobiliário hospitalar",
        keywords={
            # Equipamentos medicos gerais
            "equipamento medico",
            "equipamento hospitalar",
            "equipamentos hospitalares",
            "aparelho medico",
            # Diagnostico por imagem
            "raio x",
            "aparelho de raio-x",
            "ultrassom",
            "ultrassonografia",
            "tomografo",
            "tomografia",
            "ressonancia magnetica",
            # Monitoramento e suporte a vida
            "desfibrilador",
            "desfibriladores",
            "monitor multiparametro",
            "monitor cardiaco",
            "ventilador pulmonar",
            "respirador mecanico",
            "bomba de infusao",
            "incubadora neonatal",
            "incubadora",
            "aparelho de anestesia",
            # Esterilizacao
            "autoclave",
            "autoclaves",
            "estufa hospitalar",
            "estufa de esterilizacao",
            # Laboratorio
            "microscopio",
            "centrifuga laboratorial",
            "centrifuga",
            "eletrocardiografo",
            "ECG",
            "eletroencefalografo",
            # Instrumentos de medicao
            "oximetro",
            "esfigmomanometro",
            "estetoscopio",
            # Mobilidade e acessibilidade hospitalar
            "cama hospitalar",
            "camas hospitalares",
            "maca",
            "maca hospitalar",
            "cadeira de rodas",
            "cadeiras de rodas",
            "muleta",
            "muletas",
            "andador",
            "andadores",
            # Orteses, proteses e materiais especiais
            "ortese",
            "orteses",
            "protese",
            "proteses",
            "OPME",
            # Centro cirurgico
            "mesa cirurgica",
            "foco cirurgico",
            "foco de luz cirurgico",
            # Odontologia
            "cadeira odontologica",
            "compressor odontologico",
            "fotopolimerizador",
            "equipo odontologico",
        },
        exclusions={
            # Informatica (evitar confusao com "monitor")
            "equipamento de informatica",
            "equipamento de escritorio",
            "monitor de video",
            "monitor LCD",
            "monitor LED",
            # Mobiliario (evitar confusao com "mesa", "cadeira")
            "mesa de escritorio",
            "mesa de reuniao",
            "cadeira de escritorio",
            "cadeira giratoria",
            # Respirador como EPI generico
            "respirador de EPI",
            "respirador descartavel",
            # Centrifuga industrial
            "centrifuga industrial",
            "centrifuga de acucar",
        },
        search_keywords=["equipamento hospitalar", "equipamento medico", "cama hospitalar", "autoclave", "raio-x"],
        valor_min=5_000.0,
        valor_max=50_000_000.0,
    ),
    "servicos_gerais": SectorConfig(
        id="servicos_gerais",
        name="Serviços Gerais e Manutenção",
        description="Manutenção predial, facilities, jardinagem, controle de pragas, portaria, zeladoria",
        keywords={
            # Termos gerais
            "servicos gerais",
            "servico terceirizado",
            "terceirizacao",
            "facilities",
            "facility management",
            # Manutencao predial (HVAC, elevadores)
            "manutencao de ar condicionado",
            "manutencao de climatizacao",
            "manutencao de elevador",
            "manutencao de elevadores",
            # Jardinagem e paisagismo
            "jardinagem",
            "paisagismo",
            "poda de arvore",
            "poda de arvores",
            "rocagem",
            "rocada",
            # Controle de pragas
            "controle de pragas",
            "dedetizacao",
            "desinsetizacao",
            "desratizacao",
            # Portaria e recepcao
            "servico de portaria",
            "porteiro",
            "porteiros",
            "recepcao",
            "recepcionista",
            "servico de recepcao",
            # Copa e copeiragem
            "copeiragem",
            "copeiro",
            "copeira",
            # Lavanderia
            "lavanderia hospitalar",
            "lavanderia industrial",
            # Zeladoria
            "zeladoria",
            "zelador",
            # Prevencao e combate a incendio
            "brigada de incendio",
            "AVCB",
            "PPCI",
            "recarga de extintor",
            "extintor de incendio",
            # Manutencao de sistemas prediais
            "manutencao de grupo gerador",
            "grupo gerador",
            "manutencao eletrica",
            "manutencao hidraulica",
            "manutencao de subestacao",
            "manutencao preventiva predial",
            # Servicos especificos
            "limpeza de caixa d'agua",
            "manutencao de piscina",
            "tratamento de piscina",
        },
        exclusions={
            # Manutencao em contexto de TI
            "manutencao de software",
            "manutencao de sistema",
            "manutencao de rede",
            "manutencao de computador",
            # Manutencao veicular (setor veiculos)
            "manutencao de veiculo",
            "manutencao de frota",
            "manutencao veicular",
            "manutencao automotiva",
            # Manutencao de equipamento medico (setor hospitalar)
            "manutencao de equipamento medico",
            "manutencao de equipamento hospitalar",
            # Manutencao de infraestrutura viaria (setor engenharia)
            "manutencao de estrada",
            "manutencao de rodovia",
            "manutencao de ponte",
            "manutencao de pavimento",
            # Servicos intelectuais/profissionais (nao sao servicos gerais)
            "servico de consultoria",
            "servico de auditoria",
            "servico de contabilidade",
            "servico juridico",
            # "terceirizacao" em contexto generico/politico
            "lei de terceirizacao",
            "reforma trabalhista",
        },
        search_keywords=["servicos gerais", "manutencao predial", "jardinagem", "portaria", "dedetizacao"],
        valor_min=5_000.0,
        valor_max=20_000_000.0,
    ),
    "seguranca": SectorConfig(
        id="seguranca",
        name="Segurança e Vigilância",
        description="Vigilância patrimonial, monitoramento eletrônico, controle de acesso, CFTV",
        keywords={
            # Vigilancia
            "vigilancia",
            "vigilancia patrimonial",
            "vigilancia armada",
            "vigilancia desarmada",
            "vigilante",
            "vigilantes",
            # Seguranca patrimonial (termos compostos - alta precisao)
            "seguranca patrimonial",
            "seguranca armada",
            "seguranca desarmada",
            # Monitoramento eletronico
            "monitoramento eletronico",
            "monitoramento de alarme",
            "monitoramento de alarmes",
            "camera de seguranca",
            "camera de monitoramento",
            "CFTV",
            "circuito fechado de televisao",
            "circuito fechado",
            "DVR",
            "NVR",
            "camera IP",
            "camera dome",
            # Alarmes
            "alarme",
            "alarme monitorado",
            "central de alarme",
            # Barreiras fisicas
            "cerca eletrica",
            "cerca concertina",
            "concertina",
            # Controle de acesso
            "controle de acesso",
            "catraca",
            "catracas",
            "cancela",
            "cancelas",
            "torniquete",
            "portaria eletronica",
            "portaria remota",
            "guarita",
            # Biometria
            "biometria",
            "leitor biometrico",
            # Ronda e escolta
            "ronda",
            "ronda motorizada",
            "ronda noturna",
            "escolta",
            "escolta armada",
            # Deteccao
            "detector de metais",
            "detector de metal",
            "raio-x de bagagem",
        },
        exclusions={
            # Seguranca do trabalho / ocupacional
            "seguranca do trabalho",
            "seguranca ocupacional",
            "seguranca e saude do trabalho",
            "SESMT",
            "CIPA",
            # Seguranca alimentar
            "seguranca alimentar",
            "seguranca nutricional",
            # Seguranca da informacao / cyber
            "seguranca da informacao",
            "seguranca cibernetica",
            "cybersecurity",
            "ciberseguranca",
            # Seguranca publica (policia, nao terceirizado)
            "seguranca publica",
            "defesa nacional",
            # Outros contextos de "seguranca"
            "seguranca viaria",
            "seguranca no transito",
            "seguranca sanitaria",
            "seguranca juridica",
            "seguranca hidrica",
            # Vigilancia em contexto nao-patrimonial
            "vigilancia sanitaria",
            "vigilancia epidemiologica",
            "vigilancia em saude",
            # Orgaos/conselhos (nao sao servicos)
            "conselho de seguranca",
            "secretaria de seguranca",
            # "alarme" em contexto nao-seguranca
            "alarme falso",
            "falso alarme",
            # "vigilancia" in public health/environmental context
            "vigilancia de vetores",
            "vigilancia de zoonoses",
            "vigilancia ambiental",
        },
        search_keywords=["vigilancia patrimonial", "CFTV", "controle de acesso", "camera de seguranca", "vigilante"],
        valor_min=10_000.0,
        valor_max=20_000_000.0,
    ),
}


def get_sector(sector_id: str) -> SectorConfig:
    """
    Get sector configuration by ID.

    Args:
        sector_id: Sector identifier (e.g., "vestuario", "alimentos")

    Returns:
        SectorConfig for the requested sector

    Raises:
        KeyError: If sector_id not found
    """
    if sector_id not in SECTORS:
        raise KeyError(f"Setor '{sector_id}' não encontrado. Setores disponíveis: {list(SECTORS.keys())}")
    return SECTORS[sector_id]


def list_sectors() -> list[dict]:
    """
    List all available sectors for frontend consumption.

    Returns:
        List of dicts with id, name, description for each sector.
    """
    return [{"id": s.id, "name": s.name, "description": s.description} for s in SECTORS.values()]
